import * as pdfjsLib from 'https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.mjs';
    pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.mjs';
    const VERSION='definitivo-v14';
    const pdfInput=document.getElementById('reciboPdf'),btnCalcular=document.getElementById('btnCalcular'),alertBox=document.getElementById('alertBox'),resultCard=document.getElementById('resultCard'),cupoFinalEl=document.getElementById('cupoFinal'),resultNoteEl=document.getElementById('resultNote'),resultMetaEl=document.getElementById('resultMeta');
    const money=new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',minimumFractionDigits:2,maximumFractionDigits:2});
    function showAlert(t,m){alertBox.className=`alert show ${t}`;alertBox.textContent=m}function clearAlert(){alertBox.className='alert';alertBox.textContent=''}function resetResult(){resultCard.classList.remove('show','negative');cupoFinalEl.textContent=money.format(0);resultNoteEl.textContent='Resultado calculado sobre el PDF cargado.';resultMetaEl.innerHTML=''}
    function round2(v){return Math.round((Number(v)+Number.EPSILON)*100)/100}function cleanText(v){return String(v||'').replace(/\s+/g,' ').trim()}
    function parseMoney(raw){if(!raw)return 0;let s=String(raw).replace(/\$/g,'').replace(/\s/g,'').replace(/[^\d,.-]/g,'');const c=s.lastIndexOf(','),d=s.lastIndexOf('.');if(c>=0&&d>=0){if(c>d){s=s.replace(/\./g,'').replace(',','.')}else{s=s.replace(/,/g,'')}}else if(c>=0){s=s.replace(',','.')}const n=Number(s);return Number.isFinite(n)?n:0}
    const MONEY_REGEX=/(?<![\d.,])-?\$?\s*\d[\d.,]*[.,]\d{2}(?![\d.,])/g;
    function moneyValues(text){return (String(text||'').match(MONEY_REGEX)||[]).map(parseMoney).filter(v=>Number.isFinite(v))}function lastMoney(text){const v=moneyValues(text);return v.length?v[v.length-1]:0}
    async function extractPdfText(file){const buffer=await file.arrayBuffer();const pdf=await pdfjsLib.getDocument({data:buffer,useSystemFonts:true}).promise;const rows=[],items=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p);const content=await page.getTextContent();const buckets=[];for(const item of content.items){const text=cleanText(item.str);if(!text)continue;const tr=item.transform||[];const x=Number(tr[4]||0),y=Number(tr[5]||0);items.push({page:p,x,y,text});let row=buckets.find(r=>Math.abs(r.y-y)<=3.2);if(!row){row={y,items:[]};buckets.push(row)}row.items.push({x,text})}buckets.sort((a,b)=>b.y-a.y).forEach(row=>{row.items.sort((a,b)=>a.x-b.x);const line=cleanText(row.items.map(i=>i.text).join(' '));if(line)rows.push(line)})}items.sort((a,b)=>a.page!==b.page?a.page-b.page:(Math.abs(a.y-b.y)>3.2?b.y-a.y:a.x-b.x));const globalText=cleanText(items.map(i=>i.text).join(' '));return{rows,globalText}}
    function findLine(lines,regex){return lines.find(line=>regex.test(line))||''}
    function findAmountByCode(lines,globalText,code,fallbackRegex){const codeRegex=new RegExp(`\\b${code}\\b`);const row=findLine(lines,codeRegex);if(row){const value=lastMoney(row);if(value>0)return round2(value)}const idx=globalText.search(codeRegex);if(idx>=0){const slice=globalText.slice(idx,idx+160);const values=moneyValues(slice).filter(v=>v>0);if(values.length)return round2(values[values.length-1])}const idxFallback=globalText.search(fallbackRegex);if(idxFallback>=0){const slice=globalText.slice(idxFallback,idxFallback+160);const values=moneyValues(slice).filter(v=>v>0);if(values.length)return round2(values[values.length-1])}return 0}
    function findTotals(lines,globalText){for(const line of lines){const values=moneyValues(line);if(values.length>=3){const [a,b,c]=values.slice(-3);if(a>500000&&c>500000){return{haberesConAporte:round2(a),haberesSinAporte:round2(b),totalDescuentos:round2(c),source:'fila_totales',raw:line}}}}const values=moneyValues(globalText).filter(v=>v>0);let best=null;for(let i=0;i<=values.length-3;i++){const a=values[i],b=values[i+1],c=values[i+2];if(a>500000&&c>500000&&b>=0&&c!==a){best={haberesConAporte:round2(a),haberesSinAporte:round2(b),totalDescuentos:round2(c),source:'triple_global',raw:`${a} | ${b} | ${c}`}}}return best}
    function fallbackHaberesByCodes(lines){let total=0;for(const line of lines){const m=line.match(/\b(\d{5})\b/);if(!m)continue;const code=Number(m[1]);if(code>=10000&&code<60000){const value=lastMoney(line);if(value>0)total+=value}if(code===70000)break}return round2(total)}
    function calculate(rows,globalText){const lines=rows.map(cleanText).filter(Boolean);const totals=findTotals(lines,globalText);const haberes=totals?.haberesConAporte||fallbackHaberesByCodes(lines);const totalDescuentosRecibo=totals?.totalDescuentos||0;const ips=findAmountByCode(lines,globalText,'70000',/i\.?\s*p\.?\s*s|ips\s*14/i);const ioma=findAmountByCode(lines,globalText,'70020',/i\.?\s*o\.?\s*m\.?\s*a|ioma/i);if(!haberes||!ips||!ioma||!totalDescuentosRecibo){return{success:false,message:'No se pudieron detectar todos los importes principales del recibo.',debug:{version:VERSION,haberes,ips,ioma,totalDescuentosRecibo,totals,rowsPreview:lines.slice(0,100),globalPreview:globalText.slice(0,3500)}}}const descuentosDebajoIoma=round2(totalDescuentosRecibo-ips-ioma);const resultadoX=round2(haberes-ips-ioma);const base75=round2(resultadoX*.75);const cupoFinal=round2(base75-descuentosDebajoIoma);return{success:true,cupoFinal,resumen:{haberes:round2(haberes),ips:round2(ips),ioma:round2(ioma),resultadoX,base75,totalDescuentosRecibo:round2(totalDescuentosRecibo),descuentosDebajoIoma,fuenteTotales:totals?.source||'fallback'}}}
    async function calcularCupo(){const file=pdfInput.files[0];if(!file){showAlert('error','Adjuntá un recibo de sueldo en PDF.');return}const isPdf=file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf');if(!isPdf){showAlert('error','Solo se aceptan archivos PDF reales.');return}btnCalcular.disabled=true;btnCalcular.textContent='Analizando PDF...';showAlert('warn','Analizando recibo...');resetResult();try{const {rows,globalText}=await extractPdfText(file);const result=calculate(rows,globalText);if(!result.success){console.warn('DEBUG PDF',result.debug);throw new Error(result.message)}const cupo=Number(result.cupoFinal||0),r=result.resumen;resultCard.classList.add('show');resultCard.classList.toggle('negative',cupo<=0);cupoFinalEl.textContent=money.format(cupo);resultNoteEl.textContent=cupo<=0?'Cupo 0 o negativo. Revisar manualmente.':'Cupo positivo calculado correctamente.';resultMetaEl.innerHTML=`<div><strong>Hab. c/Ap.:</strong> ${money.format(r.haberes)}</div><div><strong>IPS:</strong> ${money.format(r.ips)}</div><div><strong>IOMA:</strong> ${money.format(r.ioma)}</div><div><strong>Total descuentos recibo:</strong> ${money.format(r.totalDescuentosRecibo)}</div><div><strong>Descuentos debajo de IOMA:</strong> ${money.format(r.descuentosDebajoIoma)}</div>`;showAlert('ok','Cupo calculado correctamente.')}catch(error){showAlert('error',error.message||'No se pudo analizar el PDF.')}finally{btnCalcular.disabled=false;btnCalcular.textContent='Calcular cupo'}}
    pdfInput.addEventListener('change',()=>{clearAlert();resetResult()});btnCalcular.addEventListener('click',calcularCupo);resetResult();
